### ISSUE TITLE
about GPU

### ISSUE THREAD

**Issue by kadenjiangse** [xuzhang1199/CLAMP#2]
Hello, I want to reproduce this model on my computer, but I don't know if the computing resources are enough. May I ask what kind of GPU is used for the experimental part of your paper? What is the minimum computing power you recommend? Hope to get your reply, thank you！

**Comment by xuzhang1199** [comment]
Thank you for your interest! We mainly use A100 as demonstrated in our paper. But other types of GPU can also be acceptable. The required computing power depends on the model you use and your own data.

**Comment by xuzhang1199** [comment]
Finished
