### ISSUE TITLE
Is it possible to release a trained models for human pose estimation on the COCO dataset?

### ISSUE THREAD

**Issue by hexiangdong2020** [xuzhang1199/CLAMP#3]
We read your article and  it was a very pretty work. But our research area is human pose estimation, not animal pose estimation. We also read in the article that you have done transfer learning from COCO human pose estimation to AP-10K animal pose estimation and should have a trained human pose model. Therfore, are you guys able to release a trained model for human pose estimation? We shall be very grateful.

**Comment by xuzhang1199** [comment]
Thanks to the great work of mmpose, it is easy to use our code to train models for human pose estimation on COCO. Please kindly refer to mmpose config files on COCO, change the dataset type to COCO, and revise the keypoints' names accordingly to adapt our work.
